apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - network-policy.yaml

namePrefix: food-app-

namespace: default

commonLabels:
  app.kubernetes.io/part-of: food-ordering-app
  app.kubernetes.io/managed-by: jenkins

images:
  - name: sangeeth108/nextjs-frontend
    newTag: latest
  - name: sangeeth108/express-backend
    newTag: latest

configMapGenerator:
  - name: app-env-config
    literals:
      - NODE_ENV=production